export const location = {
  //Goiás:
  anapolis: "Anápolis",
  catalao: "Catalão",
  goiania: "Goiânia",
  aparecidaDeGoiania: "Aperecida de Goiânia",
  trindade: "Trindade",

  //Rio Grande do Norte:
  natal: "Natal",
  mossoro: "Mossoró",
  tibauDoSul: "Pipa",
  caico: "Caicó",
  curraisNovos: "Currais Novos",

  //Acre
  rioBranco: "Rio Branco",
  cruzeiroDoSul: "Cruzeiro do Sul",
  senadorGuiomard: "Senador Guiomard",
  tarauaca: "Tarauacá",
  brasileia: "Brasileia",
};

export const coord = {
  longAnapolis: "-48.9524",
  latAnapolis: "-16.3305",
  longCatalao: "-47.9372",
  latCatalao: "-18.1721",
  longGoiania: "-49.2643",
  latGoiania: "-16.6864",
  longAparecidaDeGoiania: "-49.2464",
  latAparecidaDeGoiania: "-16.8181",
  longTrindade: "-49.2885",
  latTrindade: "-16.6517",
  longNatal: "-35.2110",
  latNatal: "-5.7945",
  longMossoro: "-37.3480",
  latMossoro: "-5.1894",
  longTibauDoSul: "-35.0862",
  latTibauDoSul: "-6.2095",
  longCaico: "-37.0980",
  latCaico: "-6.4532",
  longCurraisNovos: "-36.5173",
  latCurraisNovos: "-6.3884",
  longRioBranco: "-67.8249",
  latRioBranco: "-9.9754",
  longCruzeiroDoSul: "-73.0165",
  latCruzeiroDoSul: "-7.6339",
  longSenadorGuiomard: "-67.4580",
  latSenadorGuiomard: "-9.7161",
  longTarauaca: "-70.5903",
  latTarauaca: "-8.1480",
  longBrasileia: "-68.7584",
  latBrasileia: "-11.0680",
};
export const state = {
  goias: "Goiás",
  rioGrandeDoNorte: "Rio Grande do Norte",
  acre: "Acre",
};

export const link = {
  anapolis: "https://www.anapolis.go.gov.br/",
  catalao: "https://www.catalao.go.gov.br/",
  goiania: "https://www.goiania.go.gov.br/",
  aparecidaDeGoiania: "https://aparecida.go.gov.br/",
  trindade: "https://trindade.go.gov.br/",
  natal: "https://www.natal.rn.gov.br/",
  mossoro: "https://www.mossoro.rn.gov.br/",
  tibauDoSul: "https://tibaudosul.rn.gov.br/",
  caico: "https://www.caico.rn.gov.br/",
  curraisNovos: "https://curraisnovos.rn.gov.br/",
  rioBranco: "https://www.riobranco.ac.gov.br/",
  cruzeiroDoSul: "https://www.cruzeirodosul.ac.gov.br/",
  senadorGuiomard: "https://www.senadorguiomard.ac.gov.br/",
  tarauaca: "https://www.tarauaca.ac.gov.br/",
  brasileia: "https://www.brasileia.ac.gov.br/",
};

export const population = {
  anapolis: "415 847 hab",
  catalao: "120 789  hab",
  goiania: "1 494 599  hab",
  aparecidaDeGoiania: "550 925 hab",
  trindade: "142.431 hab",
  natal: "1.607.422 hab",
  mossoro: " 264.577 hab",
  tibauDoSul: "13 609 hab",
  caico: "61 146 hab",
  curraisNovos: "42 930 hab",
  rioBranco: "389 341 hab",
  cruzeiroDoSul: "91 888 hab",
  senadorGuiomard: "22.352 hab",
  tarauaca: "61 146 hab",
  brasileia: "212 600 hab",
};
